default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: shri_maya
  password: Master

development:
  <<: *default
  database: maya_tours_development

test:
  <<: *default
  database: maya_tours_test

production:
  <<: *default
  database: maya_tours_production
  username: maya_tours
  password: <%= ENV['MAYA_TOURS_DATABASE_PASSWORD'] %>
